### ISSUE TITLE
Abandoned? Any forked working project?

### ISSUE THREAD

**Issue by pablorsk** [davidevernizzi/docman#12]
Hi! I think this is deprecated or abandoned. Any alternatives?

**Comment by rowasc** [comment]
Hi Pablo, I am not sure the latest version is running in http://www.vernizzis.it/docman, but I updated my fork with some new instructions and got a gh-pages version of the web app running. 

You should be able to see it in action here:  https://rowasc.github.io/docman/ . Fork is at https://github.com/rowasc/docman. If you run into any problems with the fork, please open an issue there, to avoid polluting the real repo.

@davidevernizzi do you think we could move the example page to a github page in the davidevernizzi/docman repo to make it easier to update when the source code changes? I set it up as an example in my fork if you want to take a look . Thanks!

**Comment by rowasc** [comment]
Also, to clarify:  I'm not actively working on this tool, just providing some support. 

Docman is just a simple tool to visualize Postman collections and it's quite old by now. If you need advanced features and not just a way to make postman JSONs more user-friendly, something like apiary or swagger will be a better choice.

**Comment by pablorsk** [comment]
WOW, thanks a lot @rowasc :)

**Comment by davidevernizzi** [comment]
Sorry guys, I'm very absent :-(. I have created this project to learn react and because I needed this tool. If anyone wants to work on this he/she is more than welcome. If anyone wants to be added as an owner of the project, just ask; otherwise, fork.

I really really thank @rowasc for her commits (I owe you a beer if you ever happens to be in Italy).

**Comment by rowasc** [comment]
Hey @davidevernizzi, no need to thank me, and certainly no need to apologize.
If I'm ever in Italy  I'll buy you a beer or two for the hours this project saved me :) 

Thanks, and best of luck!
